feat: add bun support
denosaurs/deno_python pull request #47
Opened 2023-09-12 04:13 UTC by DjDeveloperr

2023-09-12 08:02 UTC, eliassjogreen approved these changes
I think it looks good for a first iteration on bun support! Great work!

2023-09-12 08:06 UTC, eliassjogreen requested changes

2023-09-12 08:06 UTC, eliassjogreen commented on plugin.ts
For bun, a dts file with
```ts
declare module "python:*";
declare module "*.py";
```
probably also makes sense.

2023-09-20 18:11 UTC, DjDeveloperr commented on plugin.ts
Hmm, but if we add this, Deno will also consider these as valid imports while Bun will not, is that right?

2023-09-21 07:43 UTC, eliassjogreen approved these changes
Nice! Good job :D

2023-09-21 11:35 UTC, merged